version: '2'

services:
  db:
     image: mysql:5.7
     volumes:
       - ./db_data:/var/lib/mysql
     ports:
       - "3306:3306"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

  wordpress:
     depends_on:
       - db
     build: ./build
     volumes:
        - ./wordpress_data:/var/www/html
        - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
    links:
      - db:db
